import { client } from "./db.js";
import { Router } from "express";
const homeRouter = Router();

stations = [
    "New Delhi",
    "Mumbai",
    "Kolkata",
    "Chennai",
    "Bengaluru",
    "Hyderabad",
    "Ahmedabad",
    "Pune",
    "Kanpur",
    "Lucknow",
    "Patna",
    "Gorakhpur",
    "Bhubaneswar",
    "Ranchi",
    "Jammu",
    "Amritsar",
    "Chandigarh",
    "Jaipur",
    "Udaipur",
    "Kota",
    "Bhopal",
    "Nagpur",
    "Itarsi",
    "Visakhapatnam",
    "Vizianagaram",
    "Tirupati",
    "Kacheguda",
    "Guntakal",
    "Secunderabad",
    "Delhi (Nizamuddin)",
    "Anand Vihar",
    "Varanasi",
    "Prayagraj",
    "Gaya",
    "Danapur",
    "Darbhanga",
    "Saharanpur",
    "Moradabad",
    "Bareilly",
    "Faridabad",
    "Agra",
    "Mathura",
    "Ratlam",
    "Surat",
    "Vadodara",
    "Solapur",
    "Kolhapur",
    "Madgaon (Goa)",
    "Ernakulam",
    "Thiruvananthapuram",
    "Kozhikode",
    "Kannur",
    "Madurai",
    "Coimbatore",
    "Salem",
    "Jolarpettai",
    "Delhi",
    "Guwahati",
    "New Jalpaiguri",
    "Siliguri",
    "Raxaul",
    "Samastipur",
    "Sonpur",
    "Muzaffarpur",
    "Jamalpur",
    "Kiul",
    "Bardhaman",
    "Asansol",
    "Durgapur",
    "Kharagpur",
    "Shalimar",
    "Jamshedpur",
    "Chakradharpur",
    "Rourkela",
    "Jharsuguda",
    "Sambalpur",
    "Brahmapur",
    "Cuttack",
    "Angul",
    "Talcher",
    "Jajpur",
    "Bilaspur",
    "Raigarh",
    "Durg",
    "Rajnandgaon",
    "Gondia",
    "Anakapalle",
    "Warangal",
    "Kazipet",
    "Malkajgiri",
    "Katpadi",
    "Arakkonam",
    "Tiruvallur",
    "Chengalpattu",
    "Chennai Egmore",
    "Tambaram",
    "Ajmer",
    "Pali",
    "Jaisalmer",
    "Bikaner",
    "Hisar",
    "Bathinda",
    "Firozpur",
    "Ludhiana",
    "Ambala",
    "Kalka",
];

homeRouter.get("/data", async (req, res) => {});

homeRouter.post("/", async (req, res) => {});

export default homeRouter;
